config/routes.rb
Jams::Application.routes.draw do

  root :to => 'videos#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  match '/signup', :to => 'users#new'
   
  resources :videos
  match '/post', :to => 'videos#search'
  match '/day', :to => 'videos#top_day'
  match '/week', :to => 'videos#top_week'
  match '/month', :to => 'videos#top_month'
  match '/alltime', :to => 'videos#top_alltime'
  match '/topweekjson', :to => 'videos#top_week_json'
  match '/playlist', :to => 'videos#playlist'
  match '/playlist_signed_out', :to => 'videos#playlist_signed_out'
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :artists, :only => [:index, :show, :destroy]
  resources :authentications, :only => [:create, :destroy]
  resources :comments
  resources :relationships, :only => [:create, :destroy]
  resources :votes, :only => [:create, :destroy]

  match '/auth/:provider/callback' => 'authentications#create'

  match '/about' => 'pages#about'

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                 :integer         not null, primary key
#  title              :string(255)
#  user_id            :integer
#  youtube_id         :string(255)
#  description        :text
#  duration           :integer
#  youtube_view_count :integer
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  votes_count        :integerVi
#

class Video < ActiveRecord::Base
  attr_accessible :title, :user_id, :youtube_id, :description, :duration, :youtube_view_count, :share_facebook, :share_twitter, :artist_id, :artist_name
  attr_accessor :share_facebook, :share_twitter, :artist_name
  
  belongs_to :user
  belongs_to :artist
  has_many :votes, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates :user_id, :presence => true, :length => { maximum: 255 }
  validates :title, :presence => true

  default_scope order: 'videos.created_at DESC'
  #scope :videos_created_at_descending, order: 'videos.created_at DESC'
  #scope :videos_votes_count_descending, order: 'videos.votes_count DESC'
  
  def to_param
    "#{id} #{title}".parameterize
  end

  def self.from_users_following(user) #Note: tutorial takes this further for scale
  	#following_ids = (user.following_ids << user.id).join(', ')
  	#where("user_id IN (#{following_ids})")
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end

  def self.top_day_videos
    day_beg = DateTime.now.in_time_zone(Time.zone).beginning_of_day
    day_end = DateTime.now.in_time_zone(Time.zone).end_of_day
    self.unscoped.find(:all, :limit => 50, :conditions => {:created_at => day_beg..day_end}, :order => "votes_count DESC")
  end

  def self.top_week_videos
    week_beg = DateTime.now.in_time_zone(Time.zone).beginning_of_week
    week_end = DateTime.now.in_time_zone(Time.zone).end_of_week
    self.unscoped.find(:all, :limit => 50, :conditions => {:created_at => week_beg..week_end}, :order => "votes_count DESC")
  end

  def self.top_month_videos
    month_beg = DateTime.now.in_time_zone(Time.zone).beginning_of_month
    month_end = DateTime.now.in_time_zone(Time.zone).end_of_month
    self.unscoped.find(:all, :limit => 50, :conditions => {:created_at => month_beg..month_end}, :order => "votes_count DESC")
  end

  def self.top_alltime_videos 
    self.unscoped.order("votes_count DESC").limit(50)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :signed_in_user, :only => [:create, :destroy]
  respond_to :html, :xml, :json
 
  def search
    #Sup
  end

  def home
    @path = root_path
    @vote = Vote.new
    @comment = Comment.new(params[:vote])
    @artists_count = Artist.all.count
    if signed_in?
      @feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 10)
      respond_with do |format|
        format.html do 
          if request.xhr?
            render :partial => 'shared/feed', :layout => false
          else
            render 'pages/home'
          end
        end
      end
    else
      @feed_items = Video.paginate(:page => params[:page], :per_page => 10)
      if request.xhr?
        render :partial => 'shared/feed'
      else
        render 'pages/home'
      end
    end
  end

  def playlist
    @tracks = Video.from_users_following(current_user).limit(30)
    respond_to do |format|
      format.json { render :json => @tracks }
    end
  end

  def playlist_signed_out
    @tracks = Video.limit(30)
    respond_to do |format|
      format.json { render :json => @tracks }
    end
  end

  def top_week_json
    @items = Video.top_week_videos
    #@artists = @items.collect {|t| t.artist.name }
    respond_to do |format|
      format.json { render :json => @items }
    end
  end

  #Pulled out common variables and partial rendering for top song methods
  #----------------------------------------------------------------------
  def top_songs_common
    @vote = Vote.new(params[:vote])
    @comment = Comment.new(params[:vote])
    respond_with do |format|
      format.html do
        if request.xhr?
          render :partial => 'shared/feed', :layout => false#, :locals => { :path => @path }
        else
          render 'sort' unless params[:page] != nil
        end
      end
    end
  end

  def index
    @feed_items = Video.paginate(:page => params[:page], :per_page => 50)
    @path = videos_path
    @header_title = "Hits"
    top_songs_common
  end

  def top_day
    @feed_items = Video.top_day_videos.paginate(:page => params[:page], :per_page => 10)
    top_songs_common
  end

  def top_week
    @feed_items = Video.top_week_videos.paginate(:page => params[:page], :per_page => 50)
    top_songs_common
  end

  def top_month
    @feed_items = Video.top_month_videos.paginate(:page => params[:page], :per_page => 10)
    top_songs_common
  end

  def top_alltime
    @feed_items = Video.top_alltime_videos.paginate(:page => params[:page], :per_page => 50)
    top_songs_common
  end

 #End top song methods
 #----------------------------------------------------------------------


  def show
    @video = Video.find(params[:id])
    @title = @video.title
    @user_videos = Video.find(params[:id]).user.videos.limit(10)
    @vote = Vote.new(params[:vote])
    @comment = Comment.new(params[:vote])
    @comment_items = @video.comments
  end


  def new
    client = YouTubeIt::Client.new
    @query = params[:v]
    @vid =  client.video_by("#{@query}")
    @video = Video.new
    @comment = Comment.new
  end

  def create
    @artist = params[:video][:artist_name]
    @artist_lookup = Artist.find_by_name(@artist)
    if @artist_lookup #If we found existing artist record
      @video = current_user.videos.build(params[:video].merge(:artist_id => @artist_lookup.id))
    else
      Artist.create_new_artist(@artist)
      @artist_lookup = Artist.find_by_name(@artist)
      @video = current_user.videos.build(params[:video].merge(:artist_id => @artist_lookup.id))
    end
    if @video.save
      flash[:success] = "Your Video is now live. #{ActionController::Base.helpers.link_to "Close", '#'}".html_safe
      facebook_share(params[:video], @video) #If the user has selected the checkbox to share on Facebook
      twitter_share(params[:video])          #If the user has selected the checkbox to share on Twitter
      redirect_to root_path
    else
      flash[:error] = "Something went wrong with your video. We're looking into it."
      redirect_to root_path
    end
  end

  def edit
    @video = Video.find(params[:id])
    @artist = @video.artist
  end

  def update
    @video = Video.find(params[:id])
    @artist = params[:video][:artist_name]
    @artist_lookup = Artist.find_by_name(@artist)
    if @artist_lookup
      if @video.update_attributes(params[:video].merge(:artist_id => @artist_lookup.id))
        flash[:success] = "Your video was updated successfully. #{ActionController::Base.helpers.link_to "Close", '#'}".html_safe
        redirect_to @video
      else
        render 'edit'
      end
    else
      Artist.create_new_artist(@artist)
      @artist_lookup = Artist.find_by_name(@artist)
      if @video.update_attributes(params[:video].merge(:artist_id => @artist_lookup.id))
        flash[:success] = "Your video was updated successfully. #{ActionController::Base.helpers.link_to "Close", '#'}".html_safe
        redirect_to @video
      else
        render 'edit'
      end
    end
  end

  def destroy
    Video.find(params[:id]).destroy
    flash[:success] = "Your video was deleted. Good riddance. #{ActionController::Base.helpers.link_to "Close", '#'}".html_safe
    redirect_to root_path
  end

  def twitter_share(params)
    if params[:share_twitter] == "1"
      begin
        token = current_user.authentications.where(:provider => "twitter")[0].token
        secret = current_user.authentications.where(:provider => "twitter")[0].secret
        message = "#{params[:title]} on @thepaintapp:" + " #{request.protocol}#{request.host_with_port}#{request.fullpath}/#{@video.id}" 
        current_user.share_video_twitter(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, token, secret, message)
      rescue
        flash[:error] = "There was a problem sharing your video. We're looking into it. #{ActionController::Base.helpers.link_to "Close", '#'}".html_safe
      end
    end
  end

  def facebook_share(params, video)
    if params[:share_facebook] == "1"
      begin
        token = current_user.authentications.where(:provider => "facebook")[0].token
        message = ""
        title = video.title
        url_extension = "#{video.id} #{title}".parameterize
        url = "#{request.protocol}#{request.host_with_port}#{request.fullpath}/#{url_extension}"
        caption = MESSAGE
        description = video.description
        thumb_url = "http://i.ytimg.com/vi/#{video.youtube_id}/default.jpg"
        target = ""
        current_user.share_video_facebook(token, message, title, url, caption, description, thumb_url, target)
      rescue
        flash[:error] = "There was a problem sharing your video. We're looking into it. #{ActionController::Base.helpers.link_to "Close", '#'}".html_safe
      end
    end    
  end

end

app/views/videos/_comment_item.html.erb
<div class="comment-item" id="comment-<%= comment_item.id %>">
	<div class="comment-image">
		<a href="<%= user_path(comment_item.user) %>">
			<% unless comment_item.user.image.nil? %>
				<img src="<%= comment_item.user.image %>" title="<%= comment_item.user.username %>" />
			<% else %>
				<%= image_tag "default.png", :title => comment_item.user.username %>
			<% end %>
		</a>
	</div>
	<div class="comment-username">
		<%= link_to comment_item.user.username, comment_item.user %>
		<p><%= comment_item.content %></p>
	</div>
	<div class="comment-time">
		<% if current_user?(comment_item.user) %>
			<%= link_to "", comment_item, :method => :delete, :class => "comment-delete", :id => "comment-delete-#{comment_item.id}", :title => "Delete comment" %>
		<% end %>
	</div>
</div>

app/views/videos/_social.html.erb
<% url = "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>
<div class="fb-like" data-href="<%= url %>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div>
<div class="floatleft" style="width: 90px;margin-left: 14px;"><a class="twitter-share-button" data-via="thepaintapp" style="margin-left: 14px;" href="https://twitter.com/share/tweet?
	original_referer=<%= url %>
	&amp;source=tweetbutton
	&amp;text=<%= @video.title %>
	&amp;url=<%= url %>
	&amp;via=thepaintapp">Tweet</a>
</div>
<a class="pin-it-button" count-layout="horizontal" href="http://pinterest.com/pin/create/button/?
	url=<%= url %>
	&amp;media=http://i.ytimg.com/vi/<%= @video.youtube_id %>/hqdefault.jpg
	&amp;description=<%= @video.title %>"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>

app/views/videos/_unvote_newsfeed.html.erb
<span class="heart voted"></span>

app/views/videos/edit.html.erb
<div class="left-container">
  <div class="new-track">
  <h1>Update your track</h1>
  <a href="<%= root_path %>">&#8249;&#8249;Back</a>
  <% if @video.errors.any? %>
    <div class="alert">
      <ul class="error-list unstyled">
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="player">
    <iframe title='YouTube video player' width='620' height='340' src='http://www.youtube.com/embed/<%= @video.youtube_id %>?wmode=opaque' frameborder='0' allowfullscreen></iframe>
  </div>
  <%= form_for(@video) do |f| %>
    <ul class="form unstyled">
      <li style="margin-left: 36px;">Artist
        <div class="artist"></div>
        <% @artist.nil? ? artist = "" : artist = @artist.name %>
        <%= f.text_field :artist_name, :value => artist, :class=> "image-round-3", :id => "artist", :size => "53", :maxlength => "155", :autocomplete => "off" %>
      </li>
      <li style="margin-left: 45px;">Title
        <div class="title"></div>
        <%= f.text_field :title, :value => @video.title, :class=> "image-round-3", :size => "53", :maxlength => "155", :autocomplete => "off" %>
      </li>
      <li>Comment
        <div class="comment"></div>
        <%= f.text_field :description, :value => @video.description, :class=> "image-round-3", :size => "53", :maxlength => "255", :autocomplete => "off" %>
      </li>
    </ul>
    <span class="button post-button floatright">
      <div class="post"></div>
      <%= f.submit "Update" %>
    </span>
  <% end %>
  <%= link_to "Delete", @video, :confirm => 'Are you sure you want to delete this track?', :method => :delete %>
  </div>
</div>

app/views/videos/new.html.erb
<script type="text/javascript">
  $("document").ready( function() {
    var has_facebook = "<%= current_user.has_facebook?.present? %>";
    var has_twitter = "<%= current_user.has_twitter?.present? %>";
    if (has_facebook == "false") {
      $("#connect-facebook").show();
      $("#share-facebook").attr('disabled','disabled');
      $("#facebook").css('color','#999');
    }
    else {
      //$("#share-facebook").attr('checked','checked');
    }
    if (has_twitter == "false") {
      $("#connect-twitter").show();
      $("#share-twitter").attr('disabled','disabled');
      $("#twitter").css('color','#999');
    }
    else {
      //$("#share-twitter").attr('checked','checked');
    }

    var title = '<%= raw @vid.title %>';
    //alert(title);
    title = title.toLowerCase().replace(/\b[a-z]/g, function(letter) {
      return letter.toUpperCase();
    });
    title = title.replace(/ *\[[^)]*\] */g, "").replace(/ *\([^)]*\) */g, "");
    var splitTitle = title.split(/[,-]+/);
    //var splitTitle = title.split("Ft.","-");
    //alert(splitTitle.length);
    if (splitTitle.length > 1){
      $("#artist").val(splitTitle[0].trim());
      $("#title").val(splitTitle[1].trim());
    }

  });
</script>

<div class="left-container">
  <div class="new-track">
    <h1>Preview and Post</h1>
    <h2><%= @vid.title %></h2>
    <a href="<%= root_path %>">&#8249;&#8249;Back</a>
    <% if @video.errors.any? %>
      <div class="alert">
        <ul class="error-list unstyled">
        <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="player">
      <iframe title='YouTube video player' width='620' height='340' src='http://www.youtube.com/embed/<%= @vid.video_id.split(":").last %>?wmode=opaque' frameborder='0' allowfullscreen></iframe>
    </div>
    <%= form_for(@video) do |f| %>
      <ul class="form unstyled">
        <li style="margin-left: 36px;">Artist
          <div class="artist"></div>
          <%= f.text_field :artist_name, :class=> "image-round-3", :id => "artist", :size => "53", :maxlength => "155", :autocomplete => "off" %>
        </li>
        <li style="margin-left: 45px;">Title
          <div class="title"></div>
          <%= f.text_field :title, :class=> "image-round-3", :id => "title", :size => "53", :maxlength => "155", :autocomplete => "off" %>
        </li>
        <li>Comment
          <div class="comment"></div>
          <%= f.text_field :description, :class=> "image-round-3", :size => "53", :maxlength => "255", :autocomplete => "off" %>
          <%= f.hidden_field :youtube_id, :value => @vid.video_id.split(":").last %>
          <%= f.hidden_field :duration, :value => @vid.duration %>
        </li>
      </ul>
      <div class="share">
        <div id="facebook">
          <%= f.check_box :share_facebook, :id => "share-facebook" %>
          <div class="facebook"></div>
          <%= f.label :share_facebook, "Share on Facebook" %><a href="/auth/facebook" id="connect-facebook" style="display:none;" target="_blank">Connect account</a>
        </div>
        <div id="twitter">
          <%= f.check_box :share_twitter, :id => "share-twitter" %>
          <div class="twitter"></div>
          <%= f.label :share_twitter, "Share on Twitter" %><a href="/auth/twitter" id="connect-twitter" style="display:none;" target="_blank">Connect account</a>
        </div>
      </div>
      <span class="button post-button floatright">
        <div class="post"></div>
        <%= f.submit "Post" %>
      </span>
    <% end %>
  </div>
</div>

app/views/videos/search.html.erb
<%= render 'shared/search' %>

app/views/videos/show.html.erb
<% content_for :head do  %>
	<%= render :partial => 'layouts/fb_ogo' %>
<% end %>

<% if signed_in? %>
<script type="text/javascript">
  $("document").ready( function() {
    $("#vote").click(function() {
		  var video_id = "<%= @video.id %>";
		  var current_user_id = "<%= current_user.id %>";
		  addPointOnMedia(video_id,current_user_id);
    });	
    addCommentOnMedia();
    deleteComment();
  });
</script>
<% end %>

<div class="left-container">
  <div class="video-main">
	<div class="video-header">
	  <div class="name"><%= @video.title %>
	    <% if current_user?(@video.user) %><a class="edit-media" href="<%= edit_video_path(@video.id) %>" title="Edit #{@video.title}"><div class="edit"></div>Edit track</a><% end %>
	  </div>
	  <% unless @video.artist.nil? %><div class="name artist">by <a href="<%= artist_path(@video.artist) %>"><%= @video.artist.name %></a></div><% end %>
	  <div class="left">
		<div class="created-at">
		  <% @video.user.image == nil ? image = "/assets/default-small.png" : image = @video.user.image %>
		  <a href="<%= user_path(@video.user.id) %>"><img src="<%= image %>" /><%= @video.user.username %></a><div class="clock"></div><%= time_ago_in_words(@video.created_at) %> ago
		</div>
	  </div>
	  <a href="http://youtube.com/watch?v=<%= @video.youtube_id %>" class="right" target="_blank">Powered by<div class="powered"></div></a>
	</div>
	<div class="video-player">
	  <iframe title='YouTube video player' width='620' height='380' src='http://www.youtube.com/embed/<%= @video.youtube_id %>?wmode=opaque' frameborder='0' allowfullscreen></iframe>
	  <% unless @video.description.empty? %>
	    <p class="video-description"><%=raw @video.description.gsub(/\n/, '<br/>') %></p>
	  <% end %>
	  <div class="video-social">
	  	<div id="video-votes" class="floatleft">
	    <% if signed_in? %>
	      <% unless current_user.vote?(@video.id) %>
			<span class="button button-hover" id="vote"><div class="sunglasses"></div></span>
		  <% else %>
		  	<span class="button voted"><div class="sunglasses"></div></span>
		  <% end %> 
	    <% else %>
		<span class="button button-hover" onclick="window.location='/signin' "><div class="sunglasses"></div></span>
	    <% end %>
	  </div>
	    <%= render '/videos/social' %>
	  </div>
	</div>
	<div class="video-points-and-comments-container">
	  <div class="video-votes-container">
		<div class="video-subheader" id="points-value"><%= pluralize(@video.votes_count, 'point') %></div>
		  <div id="points-container">
		    <% @video.votes.each do |v| %>
			    <% v.user.image == nil ? image = "/assets/default-small.png" : image = v.user.image %>
				  <a href="<%= user_path(v.user) %>"><img src="<%= image %>" title="<%= v.user.username %>" /></a>
		    <% end %>
		  </div>
	  </div>
	</div>
	<div id="comments-container">
	  <div class="video-subheader" id="comments-count"><%= pluralize(@video.comments.count, 'comment') %></div>
	  <%= render :partial => 'videos/comment_item', :collection => @comment_items %>
	  <% if signed_in? %>
	    <div id="comment-form-container" class="comment-form-container">
		<% current_user.image == nil ? image = "/assets/default-small.png" : image = current_user.image %>
		  <img src="<%= image %>" class="floatleft" />
			<%= form_for(@comment, :remote => true) do |f| %>
	    	  <%= f.text_field :content, :class => "comment-input", :placeholder => "Write a comment", :maxlength => "255" %>
			  <%= f.hidden_field "video_id", :value => @video.id %><br />
	    	  <%= f.submit "Comment", class: "button floatright" %>
			<% end %>

			<script type="text/javascript">
				$input = $(".comment-input");
				if ($input.val() == "") {
					$(".button").attr('disabled', 'disabled'); //REDO
				}
			</script>

		</div>
	  <% else %>
	    <%= link_to "Sign in to comment", signin_path %>
	  <% end %>
	</div>
  </div>
</div>
<div class="right-container">
  <div class="more-from-user-container">
    <div class="more-from-user-header"><%= @video.user.username %> <span><%= @video.user.points %></span></div>
	  <% unless @user_videos.empty? %>
		<% @user_videos.each do |v| %>
		  <div class="more-from-user-item">
		    <div class="more-from-user-image">
			  <a href="<%= video_path(v) %>"><img src="http://i.ytimg.com/vi/<%= v.youtube_id %>/mqdefault.jpg" /></a>
			</div>
			<div class="more-from-video-info">
			  <a class="title" href="<%= video_path(v) %>"><%= v.title %></a>
			  <% unless v.artist.nil? %>
			  	<a class="artist" href="<%= artist_path(v.artist) %>"><%= v.artist.name %></a>
			  <% end %>
			  <div><div class="vote"></div><%= v.votes.count %></div>
			  <div><div class="comment"></div><%= v.comments.count %></div>
			</div>
		  </div>
		<% end %>
	  <% end %>
  </div>
</div>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

app/views/videos/sort.html.erb
<script>
  $(document).ready(function(){
    pagelessHTML = "<%= escape_javascript(pageless(@feed_items.total_pages, @path)) %>";
    elemIds = {'recent': '#recent', 'day': '#day', 'week': '#week', 'month': '#month', 'alltime': '#alltime'};
    loadSongs(elemIds, pagelessHTML); //Pass pageless page count in as variable, save in function to reset count.
  });
</script>

<div class="left-container">
	<div class="video-feed-header"><%= @header_title %>
    <%= link_to "Recent", videos_path, :remote => true, :id => 'recent' %>
		<%= link_to "Day", day_path, :remote => true, :id => 'day' %>
    <%= link_to "Week", week_path, :remote => true, :id => 'week' %>
    <%= link_to "Month", month_path, :remote => true, :id => 'month' %>
    <%= link_to "All time", alltime_path, :remote => true, :id => 'alltime' %>
	</div>
		<div id="results">
		  <%= render 'shared/feed' %> <!-- Render first count of feed items with render. Remaining are sent from controller
                                       after Pageless requests asynchronously -->
      <%= will_paginate @feed_items %> <!-- Keep to show pagination if JS is disabled. Requesting ?page=2 doesn't 
                                            work though as 'sort' template doesn't render to prevent multiple template requests once Pageless fires.  -->
      <%= pageless(@feed_items.total_pages, @path) %> <!-- First param is total number of pages sent back by will_paginate gem, which should descrease in count.
                                                           Second param is path to request more data.   -->
		</div>
</div>