config/routes.rb
Jams::Application.routes.draw do

  root :to => 'videos#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  match '/signup', :to => 'users#new'
   
  resources :videos
  match '/post', :to => 'videos#search'
  match '/day', :to => 'videos#top_day'
  match '/week', :to => 'videos#top_week'
  match '/month', :to => 'videos#top_month'
  match '/alltime', :to => 'videos#top_alltime'
  match '/topweekjson', :to => 'videos#top_week_json'
  match '/playlist', :to => 'videos#playlist'
  match '/playlist_signed_out', :to => 'videos#playlist_signed_out'
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :artists, :only => [:index, :show, :destroy]
  resources :authentications, :only => [:create, :destroy]
  resources :comments
  resources :relationships, :only => [:create, :destroy]
  resources :votes, :only => [:create, :destroy]

  match '/auth/:provider/callback' => 'authentications#create'

  match '/about' => 'pages#about'

end

app/views/shared/_current_track.html.erb
<div class="current-video-container">
	<h3>Your Current Track</h3>
	<div class="meta">
		<div class="points"><%= pluralize(current_user.current_video.votes_count, "point") %>, <%= pluralize(current_user.current_video.comments.count, "comment") %></div>
		<div class="active">Active: <%= time_ago_in_words(current_user.current_video.created_at) %></div>
	</div>

	<div class="image-title">
		<div class="image floatleft">
			<a href="<%= video_path(current_user.current_video) %>"><img src="http://i2.ytimg.com/vi/<%= current_user.current_video.youtube_id %>/mqdefault.jpg" /></a>
		</div>
		<div class="title floatleft">
			<a href="<%= video_path(current_user.current_video) %>" class="video-title" id="video-title"><%= current_user.current_video.title %></a>
			<a href="<%= edit_video_path(current_user.current_video) %>" class="edit-wrapper"><div class="edit"></div>Edit</a>
		</div>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul class="error-list unstyled">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<% feed_item.user.image == nil ? image = "/assets/default-small.png" : image = feed_item.user.image %>
<% if signed_in? %>
	<% current_user.vote?(feed_item.id) ? css_class = "voted" : css_class = "" %>
<% end %>
<div class="feed-container" id="container-<%= feed_item.id %>">
  <div class="image">
	<a class="user" href="<%= user_path(feed_item.user) %>"><img src="<%= image %>" class="image-round-3"/></a>
  </div>
  <div class="feed-inner">
	  <div class="user-container" id="<%= feed_item.youtube_id %>" data-id="<%= feed_item.id %>">
	    <a class="user" href="<%= user_path(feed_item.user) %>"><%= feed_item.user.username %></a>
		<span class="video-user-points"><%= feed_item.user.points %></span>
		<span class="time"><div class="clock"></div><%= time_ago_in_words(feed_item.created_at) %> ago</span>
	  </div>
	  <div class="media-container <%= css_class %>" id="media-container-<%= feed_item.id %>">
	  	<div class="cover floatleft" id="cover-<%= feed_item.id %>">
	  		<div class="play" id="play"></div>
	  	  <img class="thumb" src="http://i2.ytimg.com/vi/<%= feed_item.youtube_id %>/mqdefault.jpg"/>
	  	</div>
	  	<div class="info floatleft" id="info-<%= feed_item.id %>">
	  		<a class="title" id="title-<%= feed_item.id %>" href="<%= video_path(feed_item) %>"><%= feed_item.title %></a>
				<% unless feed_item.artist.nil? %>
					 <%= link_to feed_item.artist.name, artist_path(feed_item.artist), :class => "title artist", :id =>"artist_name-#{feed_item.id}" %>
				<% end %>	
	  		<p id="description-<%= feed_item.id %>"><%= feed_item.description %></p>
	  		<% if signed_in? && current_user.vote?(feed_item.id) %>
					<div class="actions voted" id="actions-<%= feed_item.id %>">
		  		  <span class="like"><div class="sunglasses"></div><span>Liked</span></span>
		  		</div>
		  	<% elsif signed_in? %>
		  		<div class="actions" id="actions-<%= feed_item.id %>">
		  		  <span class="like" id="vote-<%= feed_item.id %>"><div class="sunglasses"></div><span>Like</span></span>
		  		</div>
		  	<% else %>
		  		<div class="actions">
		  		  <span class="like" onclick="window.location='<%= signin_path %>'; return false;"><div class="sunglasses"></div><span>Like</span></span>
		  		</div>
		  	<% end %>
	    </div>
	  </div>
	  <div class="meta">
	  	<span><div class="sunglasses <%= css_class %>" id="sunglasses-<%= feed_item.id %>"></div><a href="javascript:;" id="points-value-<%= feed_item.id %>"><%= pluralize(feed_item.votes_count, 'person') %> liked this</a></span>
	  	<span class="dot">&#8901;</span>
	  	<span><div class="comment"></div><span id="comment-<%= feed_item.id %>"><%= pluralize(feed_item.comments.count, 'comment') %></span></span>
	  </div>
	  
		  <div class="faces" id="faces-<%= feed_item.id %>">
		  	<% unless feed_item.votes.empty? %>
		  	<% feed_item.votes.each do |u| %>
					<% u.user.image == nil ? image = "/assets/default-small.png" : image = u.user.image %>
					<a href="<%= user_path(u.user) %>"><img src="<%= image %>" title="<%= u.user.username %>" class="image-round-3"/></a>
				<% end %>
				<% end %>
		  </div>
	  
		  <div id="comments-container">
				<%= render :partial => 'videos/comment_item', :collection => feed_item.comments %>
				<% if signed_in? %>
			    <div id="comment-form-container-<%= feed_item.id %>" class="comment-form-container">
					<% current_user.image == nil ? image = "/assets/default-small.png" : image = current_user.image %>
				  <img src="<%= image %>" class="floatleft" />
						<%= form_for(@comment, :remote => true, :html => {:id => "form-#{feed_item.id}" }) do |f| %>
				    	<%= f.text_field :content, :class => "comment-input", :id => "input-#{feed_item.id}", :placeholder => "Write a comment", :maxlength => "255", :style => "width: 518px;" %>
						  <%= f.hidden_field "video_id", :value => feed_item.id %><br />
						<% end %>
					</div>
			  <% else %>
			    <a class="signin-wrapper" href="<%= signin_path %>"><div class="signin"></div>Sign in to comment</a>
			  <% end %>
		  </div>
		
		<script type="text/javascript">
			$("document").ready( function() {
				var feed_item_id = "<%= feed_item.id %>";
				var youtube_id = "<%= feed_item.youtube_id %>";

				//Add and delete comments on feed
				addCommentOnFeed(feed_item_id);
				deleteComment();

				//Play song once cover image is clicked
				playFeedTrack(youtube_id,feed_item_id);
				$("#points-value-"+feed_item_id).click(function() {
					$("#faces-"+feed_item_id).fadeToggle(150);
				});

				//Truncate long titles
				var title = "#title-"+feed_item_id;
				var description = "#description-"+feed_item_id;
				truncateText(title,60);
				truncateText(description,50);

				//Disable empty comment input
				$input = $(".comment-input");
				if ($input.val() == "") {
					$(".button").attr('disabled', 'disabled'); //REDO
				};

				//Vote
				<% if signed_in? %>
					var current_user_id = "<%= current_user.id %>";
					$("#vote-"+feed_item_id).click(function() {
						addVoteOnMedia(feed_item_id,current_user_id, true);
					});
				<% end %>

				//var $el = $('#artist_name-'+feed_item_id); //Use for remote calls for artists
				//Remote.container($el);

				/*$('#artist_name-'+feed_item_id).bind("ajax:success", function(evt, data, status, xhr){
					console.log(data);
					$('.container').html(data);
				});
*/
			});
		</script>

	</div>
</div>

app/views/shared/_playlist.html.erb
<div id="playlist-container">
  <div id="yt-player-wrapper"><div id="yt-player">Loading...</div></div>
  <ol id='track-listing'></ol>
<!--

  <a href="javascript:void(0);" onclick="play();">Play</a> | 
  <a href="javascript:void(0);" onclick="pause();">Pause</a> | 
  <a href="javascript:void(0);" onclick="stop();">Stop</a> | 
  <a href="javascript:void(0);" onclick="loadNewVideo('GrsJDy8VjZk', 0);">load</a> | 
  <a href="javascript:void(0);" onclick="halfMute(50);">Half mute</a> |
  <a href="javascript:void(0);" id="xnext">Next -></a> |
  <a href="javascript:void(0);" id="xback">Back</a>

  <div id="videoInfo">
    <p>Player state: <span id="playerState">--</span></p>
    <p>Current Time: <span id="videoCurrentTime">--:--</span> | Duration: <span id="videoDuration">--:--</span></p>
    <p>Bytes Total: <span id="bytesTotal">--</span> | Start Bytes: <span id="startBytes">--</span> | Bytes Loaded: <span id="bytesLoaded">--</span></p>
  </div>
-->
</div>

app/views/shared/_search.html.erb
<% current_user.image == nil ? image = "/assets/default-small.png" : image = current_user.image %>
<div class="search-container" id="form-search">
	<a href="javascript:;" class="search-clear" id="search-clear" style="display:none;"></a>
	<% @query = params[:s] %>
	<div class="search-wrapper">
		<img src="<%= image %>" class="floatleft image-round-3" />
		<%= form_tag("#", :method => "get", :remote => true, :class => "floatleft") do %>
		  <%= text_field_tag(:q, "#{@query}", :class => "search-input image-round-3", :placeholder => "Search for a track to post...") %>
		  <span class="button search-button"><div class="music"></div><%= submit_tag("Search", :id => 'search') %></span>
		<% end %>
	</div>
	
	<p id="loading-search" style="display:none;margin: 0 0 18px 21px;font-size: 20px;">Loading...</p>
</div>
<div id="search-results" class="search-results"></div>

<script type="text/javascript">
	$("document").ready( function () {

		$("#search").click( function() {
			var input = $("#q").val();
			if (input != 0) {
				$("#search-results").empty();
				$("#loading-search").fadeIn(100);
				var input = $("#q").val();
				getSongs(input);
			}	
		});

		$("#search-clear").click( function() {
			$("#search-results").empty();
			$("#q").val("");
			$(this).hide();
		});

		$("#q").keyup( function(){
			$("#search-clear").show();
		});

	});
</script>

app/views/shared/_social.html.erb
<div class="social">
	<p>Paint the Town is better social</p>
		<% unless current_user.has_facebook?.present? %>
			<a href="/auth/facebook/"><div class="facebook"></div>Connect to Facebook</a>
		<% end %>
		<% unless current_user.has_twitter?.present? %>
			<a href="/auth/twitter/"><div class="twitter"></div>Connect to Twitter</a>
		<% end %>
		</ul>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats-container">
	<h3>Stats</h3>
	<div class="stats">
		<a href="<%= user_path(@user) %>"><div class="sunglasses"></div><%= pluralize(@user.points, "point") %></a>
		<a href="<%= user_path(@user) %>"><div class="tracks"></div><%= pluralize(@user.videos.count, "track") %></a>
		<a href="<%= followers_user_path(@user) %>"><div class="followers"></div><%= pluralize(@user.followers.count, "follower") %></a>
		<a href="<%= following_user_path(@user) %>"><div class="following"></div><%= @user.following.count %> following</a>
	</div>
</div>

app/views/shared/_users.html.erb
<% @users.each do |u| %>
	<div class="user-listing-container">
		<div class="user-image">
			<a href="<%= user_path(u) %>">
				<% unless u.image.nil? %>
					<img src="<%= u.image %>" title="<%= u.username %>" />
				<% else %>
					<%= image_tag "default.png", :title => u.username %>
				<% end %>
			</a>
		</div>
		<div class="user-listing-wrapper">
			<ul class="unstyled user-listing">
				<li class="user-name"><%= link_to u.username, u %>
					<% unless u.points.nil? %>
						<span><%= u.points %></span>
					<% end %>
				</li>
				<li class="user-description">Joined about <%= time_ago_in_words(u.created_at) %> ago</li>
				<% unless u.videos.first.nil? %>
				<li class="user-video">Current video: <%= link_to u.videos.first.title, u.videos.first %></li>
				<% end %>
			</ul>
		</div>
		<% if signed_in? %>
			<div class="user-follow-container">
				<div class="user-follow">
					<% @user = u %>
					<%= render 'users/follow_form' %>
				</div>
			</div>
		<% end %>
	</div>
<% end %>