config/routes.rb
Jams::Application.routes.draw do

  root :to => 'videos#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  match '/signup', :to => 'users#new'
   
  resources :videos
  match '/post', :to => 'videos#search'
  match '/day', :to => 'videos#top_day'
  match '/week', :to => 'videos#top_week'
  match '/month', :to => 'videos#top_month'
  match '/alltime', :to => 'videos#top_alltime'
  match '/topweekjson', :to => 'videos#top_week_json'
  match '/playlist', :to => 'videos#playlist'
  match '/playlist_signed_out', :to => 'videos#playlist_signed_out'
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :artists, :only => [:index, :show, :destroy]
  resources :authentications, :only => [:create, :destroy]
  resources :comments
  resources :relationships, :only => [:create, :destroy]
  resources :votes, :only => [:create, :destroy]

  match '/auth/:provider/callback' => 'authentications#create'

  match '/about' => 'pages#about'

end

app/views/pages/about.html.erb
<% unless signed_in? %>
    <% content_for :hero do  %>
        <%= render :partial => 'layouts/hero' %>
    <% end %>
<% end %>

<div class="left-container">
  <div class="about">
    <h1>What is Paint Hip Hop?</h1>
    <p>Paint Hip Hop is a hip hop music app. We built the site to showcase and share the best and newest rap tunes without any clutter.</p>
    <p>You know that song throughout the day that <a href="http://paintapp.co/videos/219-zip-a-double-cup" target="_blank">gets you pumped up</a> or <a href="http://paintapp.co/videos/625-all-gold-everything" target="_blank">stuck in your head</a>? This is the place to share it - follow people with similar music tastes and discover rap tunes you didn't know about.</p>
    <h2>How does it work?</h2>
    <p>Find people with music tastes you like and follow them. When they share music, it will show up in your feed. This is also how your playlist is built - it's a changing list of what your friends are listening to and sharing.</p>
    <p>To post a track, search for a song at the top of your feed. Once the song is shared, it will be sent to all the people that follow you and will also show up in their playlists. Swag.</p>
    <p>Popular tracks will earn you rep points. Rep points are achieved by people liking your track.</p>
    <h2>Who runs the site?</h2>
    <p>The site was built by <a href="http://paintapp.co/users/4-rap-game-bill-clinton" target="_blank">Reza Parang</a>. If you have any questions or run into any issues, <a href="https://twitter.com/RezaParang" target="_blank">send a message on Twitter</a> and I'll get to it as soon as possible.</p>
    <p>Thanks for checking the site out - Much love.</p>
  </div>
</div>
<div class="right-container">
    <img src="/assets/logo-big.png" />
</div>

app/views/pages/home.html.erb
<script type="text/javascript">
	$("document").ready( function() {
    var elemIds = {'feed': '#feed', 'recent': '#recent', 'people': '#people', 'day': '#day', 'week': '#week', 'month': '#month', 'alltime': '#alltime'};
    var pagelessHTML = "<%= escape_javascript(pageless(10, @path)) %>";
    getTrending("<%= escape_javascript(topweekjson_path) %>");
    filterFeed(elemIds, pagelessHTML, "<%= @feed_items.total_pages %>");
	})
</script>

<% if signed_in? %>
	<div class="left-container">

		<div class="feed-options">
			<div class="floatleft">
				<%= link_to raw("<div class='feed'></div>Feed"), root_path, :remote => true, :id => 'feed' %>
				<%= link_to raw("<div class='new'></div>New"), videos_path, :remote => true, :id => 'recent' %>
				<%= link_to raw("<div class='people'></div>People"), users_path, :remote => true, :id => 'people' %>
			</div>
			<div class="loading floatleft" style="display:none;" id="loading-feed"></div>
			<div class="floatright">
				<div class="top"></div>Top:
				<%= link_to "Week", week_path, :remote => true, :id => 'week' %>
		    <%= link_to "Month", month_path, :remote => true, :id => 'month' %>
		    <%= link_to "All", alltime_path, :remote => true, :id => 'alltime' %>
			</div>
		</div>

		<%= render 'shared/search' %>

		<% unless current_user.feed.empty? %>
			<div id="results">
			  <%= render 'shared/feed' %> <!-- Render first count of feed items with render. -->
	      <%= will_paginate @feed_items %> <!-- Keep to show pagination if JS is disabled. -->
	      <%= pageless(@feed_items.total_pages, @path) %>
			</div>
		<% else %>
			<div style="padding: 30px;font-size: 20px;">You're not following anyone. Check out some <%= link_to "suggested people", users_path %>.</div>
		<% end %>
	</div>

	<div class="right-container">
		<%= render 'shared/playlist' %>
		<% unless current_user.videos.first.nil? %>
			<%= render 'shared/current_track' %>
		<% end %>
		<%= render 'shared/stats' %>
		<div class="more-from-user-container">
			<h3>Artists</h3>
			<a class="artists-count" href="<%= artists_path %>"><span><%= @artists_count %></span> total</a>
		</div>

		<div class="more-from-user-container" id="items-trending">
			<h3>Trending</h3>
			<div id="loading"></div>
		</div>

		<% unless current_user.authentications.count == 2 %>
			<%= render 'shared/social' %>
		<% end %>
	</div>

<% else %>

	<% content_for :hero do  %>
		<%= render :partial => 'layouts/hero' %>
	<% end %>

	<div class="left-container">
		<div class="feed-options">
			<div class="floatleft">
				<%= link_to raw("<div class='new'></div>New"), videos_path, :remote => true, :id => 'recent' %>
				<%= link_to raw("<div class='people'></div>People"), users_path, :remote => true, :id => 'people' %>
			</div>
			<div class="loading floatleft" style="display:none;" id="loading-feed"></div>
			<div class="floatright">
				<div class="top"></div>Top:
				<%= link_to "Week", week_path, :remote => true, :id => 'week' %>
		    <%= link_to "Month", month_path, :remote => true, :id => 'month' %>
		    <%= link_to "All", alltime_path, :remote => true, :id => 'alltime' %>
			</div>
		</div>
		<div id="results">
			<%= render 'shared/feed' %>
			<%= will_paginate @feed_items %>
			<%= pageless(@feed_items.total_pages, root_path, "#results") %>
		</div>
	</div>
	<div class="right-container">
		<%= render 'shared/playlist' %>
		<div class="more-from-user-container">
			<h3>Artists</h3>
			<a class="artists-count" href="<%= artists_path %>"><span><%= @artists_count %></span> total</a>
		</div>
		<div class="more-from-user-container" id="items-trending">
			<h3>Trending</h3>
			<div id="loading"></div>
		</div>
	</div>

<% end %>