config/routes.rb
Jams::Application.routes.draw do

  root :to => 'videos#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  match '/signup', :to => 'users#new'
   
  resources :videos
  match '/post', :to => 'videos#search'
  match '/day', :to => 'videos#top_day'
  match '/week', :to => 'videos#top_week'
  match '/month', :to => 'videos#top_month'
  match '/alltime', :to => 'videos#top_alltime'
  match '/topweekjson', :to => 'videos#top_week_json'
  match '/playlist', :to => 'videos#playlist'
  match '/playlist_signed_out', :to => 'videos#playlist_signed_out'
  
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :artists, :only => [:index, :show, :destroy]
  resources :authentications, :only => [:create, :destroy]
  resources :comments
  resources :relationships, :only => [:create, :destroy]
  resources :votes, :only => [:create, :destroy]

  match '/auth/:provider/callback' => 'authentications#create'

  match '/about' => 'pages#about'

end

app/views/layouts/_fb.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=235617383228391";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

</script>

app/views/layouts/_fb_ogo.html.erb
<meta property="fb:app_id" content="235617383228391"/>
<meta property="og:site_name" content="Paint the Town"/>
<meta property="og:type" content="video"/>
<meta property="og:url" content="<%= request.protocol + request.host_with_port + request.fullpath  %>"/>
<meta property="og:title" content="<%= @video.title %>"/>
<meta property="og:description" content="<%= @video.description %>"/>
<meta property="og:image" content="http://i.ytimg.com/vi/<%= @video.youtube_id %>/hqdefault.jpg"/>

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer-container">
		<%= link_to image_tag("skyline.png"), root_path, :class => "skyline" %>
		<div class="footer-wrapper">
			<span class="by">a project by <a href="https://twitter.com/RezaParang" target="_blank">Reza Parang</a></span>
			<ul class="unstyled">
				<li id="facebook"><div class="fb-like" data-href="https://www.facebook.com/paintapp" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div></li>
				<li id="twitter"><a href="https://twitter.com/thepaintapp" class="twitter-follow-button" data-show-count="true" data-show-screen-name="false">Follow @thepaintapp</a></li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35024794-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<% logo = image_tag("phh-logo-small.png", :alt => "Paint the Town", :class => "floatleft") %>
<nav>
  <div id="nav-wrapper">
  	<div class="nav-container">
	  <%= link_to logo, root_path, :id => "home" %>
	  <ul class="nav floatright">
	  		<li><a href="<%= about_path %>"><div class="about"></div>About</a></li>
	  	<% if signed_in? %>
			  <li><a href="<%= post_path %>"><div class="post"></div>Post track</a></li>
			  <li class="pic">
					<a href="<%= user_path(current_user) %>">
						<% unless current_user.image == nil %>
						  <img src="<%= current_user.image %>" />
						<% end %>
						<%= current_user.username %>
					</a>
			  </li>
			  <li><a href="<%= edit_user_path(current_user) %>"><div class="edit"></div></a></li>
			  <li><a href="<%= signout_path %>"><div class="signout"></div></a></li>
		  <% else %>
			  <li><a href="<%= signup_path %>">&#43;<div class="signup"></div>Sign Up</a></li>
			  <li><a href="<%= signin_path %>"><div class="signin"></div>Sign In</a></li>
			<% end %>
	  </ul>
	</div>
  </div>
</nav>

<section class="player-container glossy" id="player-container">
	<div class="player-wrapper">
		<div class="controls">
			<a href="javascript:void(0);" class="icon back" id="back"></a>
			<a href="javascript:void(0);" class="icon playing paused" id="playpause"></a>
			<a href="javascript:void(0);" class="icon next" id="next"></a>
		</div>

		<div class="music-info">
			<span id="videoCurrentTime">--:--</span> <span id="divider">|</span> <span id="videoDuration">--:--</span>
			<span id="track-name">Dirty Cup</span>
		</div>
	</div>

</section>

app/views/layouts/_hero.html.erb
<div class="hero-container">
  <div class="hero-wrapper">
    <div class="promo">
        <h6>Trinidad James, Juicy J, 2 Chainz, and hundreds more...</h6>
        <h1>The Internet's Hip Hop</h1><br />
        <h1>Music Experience</h1><br /><br />
        <h2>Discover breaking new hits in the rap world,</h2><br />
        <h2>gain rep points for posting popular tracks,</h2><br /> 
        <h2>and listen while you twerk. <a href="<%= about_path %>">Learn more</a>.</h2>
        <div class="button-wrapper">
            <a href="/auth/facebook/" class="button facebook"><div class="promo-icon facebook-icon"></div>Sign in with Facebook</a>
            <a href="<%= signup_path %>" class="button"><div class="promo-icon email-icon"></div>Sign up</a>
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    var covers = ['drake', 'juicyj', 'twochainz'];
    var random_number = Math.floor(Math.random()*3);
    cover = covers[random_number];
    $('.hero-container').addClass(cover);
</script>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Paint Hip Hop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/ga' %>
  <%= yield :head %>
</head>
<body class="<%= @black_page ? 'body-black' : ''%>">
	<%= render 'layouts/fb' %>
	<%= render 'layouts/header' %>
	<%= yield :hero %>
	<div class="container">

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>

		<%= yield %>

	</div>

	<%= render 'layouts/footer' unless request.fullpath == signup_path || request.fullpath == signin_path %>




	<script type="text/javascript">

	<% signed_in? ? path = playlist_path : path = playlist_signed_out_path  %>
	var field = new Field(0); //Track playlist index
	var playState = new Field(0); //Set default to paused play state
	var youtubeStateId = new Field(0); //Set default to 0
	var results = $.getValues("<%= escape_javascript(path) %>");

	var tracks = [];
	var track_name = [];

	$.each(results, function (i,item) {
	  track_name.push(item.title);
	  tracks.push(item.youtube_id);
	});

	function onytplayerStateChange(newState) {
	  if (newState == 0) {
	    field.setValue(field.getValue() + 1);
	    track_index = field.getValue();
	    $feed_item_id = $('#'+tracks[field.getValue()]).data('id'); //Gross hack
	    loadNewVideo(tracks[field.getValue()], track_index, $feed_item_id);
	  }
	  if (newState == 1 && playState.getValue() != "playing") {
			playState.setValue("playing");
			showPlayer();
			updateButtonPlay();
			$feed_item_id = $('#'+tracks[field.getValue()]).data('id'); //Turrible hack
			addPlayCoverStyle($feed_item_id);
		}
		if (newState == 2 && playState.getValue() != "paused") {
			playState.setValue("paused");
			updateButtonPause();
			removePlayCoverStyle();
		}
	}

	$('document').ready(function() {
		$close = $(".alert a");
		$close.click( function() {
		  $(".alert").fadeOut();
		});

		$('#playpause').click( function() {
			if ($(this).hasClass('paused')) {
				$(this).removeClass('paused')
				$feed_item_id = $('#'+tracks[field.getValue()]).data('id'); //Turrible hack
				play();
				addPlayCoverStyle($feed_item_id);
			}
			else {
				$(this).addClass('paused');
				pause();
				removePlayCoverStyle();
			}
		});

		$('#next').click( function() {
			if (field.getValue() < 29 ) {
				field.setValue(field.getValue() + 1);
		    track_index = field.getValue();
		    $feed_item_id = $('#'+tracks[field.getValue()]).data('id'); //Turrible hack
		    loadNewVideo(tracks[field.getValue()], track_index, $feed_item_id);
			}
	  });
	  $('#back').click( function() {
	  	if (field.getValue() > 0) {
		    field.setValue(field.getValue() - 1);
		    track_index = field.getValue();
		    $feed_item_id = $('#'+tracks[field.getValue()]).data('id'); //Turrible hack
		    loadNewVideo(tracks[field.getValue()], track_index, $feed_item_id);
	  	}
	  });

		initialize(field.getValue(), tracks[field.getValue()]);

	});
	</script>




</body>
</html>